
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:loan_data
    username: loan_data
    password: loan_data

  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: group1
    template:
      default-topic: topic1
server:
  port: 11015
